import argparse
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from src.data.split import all_ids, make_val_ids, repo_path
from src.utils.misc import load_config


def main():
    p = argparse.ArgumentParser()
    p.add_argument("--config", default=repo_path("configs/final.yaml"))
    p.add_argument("--out", default=repo_path("configs/val_split.txt"))
    a = p.parse_args()

    cfg = load_config(a.config)
    root = cfg.data.train_root
    ids = all_ids(root)
    val = make_val_ids(root, cfg.data.val_count, cfg.seed)

    if os.path.exists(a.out):
        print(f"{a.out} already exists -- refusing to overwrite a committed split.")
        print("Delete it explicitly if you really mean to regenerate.")
        return

    with open(a.out, "w") as f:
        f.write(f"# validation split -- held out by image, never trained on, never used for selection\n")
        f.write(f"# generated by scripts/make_split.py  seed={cfg.seed}  val_count={cfg.data.val_count}\n")
        f.write(f"# total pairs available: {len(ids)}\n")
        for v in val:
            f.write(v + "\n")

    print(f"total pairs : {len(ids)}")
    print(f"val         : {len(val)}  -> {a.out}")
    print(f"train       : {len(ids) - len(val)}")
    print(f"first val   : {val[:5]}")


if __name__ == "__main__":
    main()
